package ru.benos.everydeeds.data

import net.minecraft.resources.Identifier
import ru.benos.everydeeds.EveryDeeds

/**
 * Data packs shipped inside the mod jar (`resourcepacks/<path>`), registered by the platform layer and
 * generated by the data generator. Each one appears in the world's data pack list and can be turned off there.
 */
object DeedPacks {
    /** More milestones for every built-in set: first steps, in-between tiers and milestones for the other actions. */
    val MORE_MILESTONES: Identifier = Identifier.fromNamespaceAndPath(EveryDeeds.MOD_ID, "more_milestones")
}
